version: '3.8'

services:
  # Service MySQL
  db:
    container_name: mysql8
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: contact
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306


  php_apache:
    image: php:apache
    container_name: php_site
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  phpmya:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80